apps:
  faucet:
    port: 3000
    useCachingInterceptor: true
libs:
  common:
    network: ${NETWORK}
    urls:
      api: ${API_URL}
    database:
      host: 'localhost'
      port: 27017
      # username: 'root'
      # password: 'root'
      name: 'example'
      tlsAllowInvalidCertificates: true
    redis:
      host: '127.0.0.1'
      port: 6379
    nativeAuth:
      # maxExpirySeconds:
      acceptedOrigins:
        - utils.multiversx.com
    security:
      admins: []
    # rateLimiterSecret:
